### ISSUE TITLE
Median filter should not be done in-place

### ISSUE THREAD

**Issue by 3c1u** [hmdlab/frame_diff#2]

**Comment by Xilorole** [comment]
Hi @3c1u, thank you for pointing out that the median filter should not be done in-place.
As other students also pointed out, the filter must be applied at once after the calculation. 

We were not applying the change before the classes end due to the codes' consistency.
We're going to change the algorithms as fast as we can.

**Comment by Xilorole** [comment]
closed by ff9cfe9
